include 'emu8086.inc'
JMP START

DATA SEGMENT 
    TOTAL        DW 20
    IDS1         DW 0000H,0001H,0002H,0003H,0004H,0005H,0006H,0007H,0008H,0009H
    IDS2         DW 000AH,000BH,000CH,000DH,000EH,000FH,0010H,0011H,0012H,0013H 
    PASSWORDS1   DB  00H,01H,02H,03H,04H,05H,06H,07H,08H,09H
    PASSWORDS2   DB  0AH,0BH,0CH,0DH,0EH,0FH,01H,02H,03H,04H
    BALANCES     DW  20 DUP (1000)

    DATA1        DB '******WELCOME*******',0
    DATA2        DB 0DH,0AH,'ENTER YOUR ID: ',0
    DATA3        DB 0DH,0AH,'ENTER YOUR PASSWORD: ',0 
    DATA4        DB 0DH,0AH,'DENIED 0  ',0  
    DATA5        DB 0DH,0AH,'ALLOWED 1 ',0 
    DATA6        DB 0DH,0AH,'******WELCOME BACK*******',0
    DATA_MENU    DB 0DH,0AH,'1. CHECK BALANCE',0DH,0AH,'2. DEPOSIT',0DH,0AH,'3. WITHDRAW',0DH,0AH,'4. EXIT',0DH,0AH,'SELECT OPTION: ',0
    DATA_BAL     DB 0DH,0AH,'CURRENT BALANCE: ',0
    DATA_DEP     DB 0DH,0AH,'ENTER AMOUNT TO DEPOSIT: ',0
    DATA_WDRAW   DB 0DH,0AH,'ENTER AMOUNT TO WITHDRAW: ',0
    DATA_OK      DB 0DH,0AH,'TRANSACTION SUCCESSFUL',0
    DATA_FAIL    DB 0DH,0AH,'INSUFFICIENT FUNDS',0

    IDINPUT      DW ? 
    PASSINPUT    DB ?
    XOR_KEY      DB 5AH
    USER_INDEX   DW ?

    RETURN_MSG   DB 'Press any key to return to menu...',0 
DATA ENDS

CODE SEGMENT

START:
    MOV AX, DATA
    MOV DS, AX  

    DEFINE_SCAN_NUM           
    DEFINE_PRINT_STRING 
    DEFINE_PRINT_NUM
    DEFINE_PRINT_NUM_UNS 

AGAIN:
    LEA SI, DATA1
    CALL PRINT_STRING
    LEA SI, DATA2
    CALL PRINT_STRING
    MOV SI, -1

    CALL SCAN_NUM
    MOV IDINPUT, CX
    MOV AX, CX
    MOV CX, 0 

L1: 
    INC CX
    CMP CX, TOTAL
    JE ERROR
    INC SI
    MOV DX, SI
    CMP IDS1[SI], AX
    JE PASS1
    CMP IDS2[SI], AX
    JE PASS2
    JMP L1

PASS1:
    LEA SI, DATA3
    CALL PRINT_STRING        
    CALL SCAN_NUM

    MOV AL, CL
    XOR AL, XOR_KEY
    MOV PASSINPUT, AL

    MOV AX, DX
    MOV DX, 2
    DIV DL
    MOV SI, AX
    MOV USER_INDEX, SI

    MOV AL, PASSINPUT
    XOR AL, XOR_KEY
    MOV AH, 0
    CMP PASSWORDS1[SI], AL
    JNE ERROR
    JMP MENU

PASS2:
    LEA SI, DATA3
    CALL PRINT_STRING        
    CALL SCAN_NUM

    MOV AL, CL
    XOR AL, XOR_KEY
    MOV PASSINPUT, AL

    MOV AX, DX
    MOV DX, 2
    DIV DL
    MOV SI, AX
    MOV USER_INDEX, SI

    MOV AL, PASSINPUT
    XOR AL, XOR_KEY
    MOV AH, 0
    CMP PASSWORDS2[SI], AL
    JNE ERROR
    JMP MENU

ERROR:
    LEA SI, DATA4
    CALL PRINT_STRING 
    PRINT 0AH
    PRINT 0DH
    JMP AGAIN

MENU:
    LEA SI, DATA5
    CALL PRINT_STRING
    PRINT 0AH
    PRINT 0DH
    LEA SI, DATA6
    CALL PRINT_STRING
    PRINT 0AH
    PRINT 0DH

MAIN_MENU:
    LEA SI, DATA_MENU
    CALL PRINT_STRING
    CALL SCAN_NUM

    CMP CX, 1
    JE CHECK_BAL
    CMP CX, 2
    JE DEPOSIT
    CMP CX, 3
    JE WITHDRAW
    CMP CX, 4
    JE EXIT
    JMP MAIN_MENU

CHECK_BAL:
    CALL CLS
    LEA SI, DATA_BAL
    CALL PRINT_STRING
    MOV SI, USER_INDEX
    MOV AX, BALANCES[SI*2]
    CALL PRINT_NUM_UNS
    CALL RETURN_TO_MENU
    JMP MAIN_MENU

DEPOSIT:
    CALL CLS
    LEA SI, DATA_DEP
    CALL PRINT_STRING
    CALL SCAN_NUM
    MOV BX, CX
    MOV SI, USER_INDEX
    ADD BALANCES[SI*2], BX
    LEA SI, DATA_OK
    CALL PRINT_STRING
    CALL RETURN_TO_MENU
    JMP MAIN_MENU

WITHDRAW:
    CALL CLS
    LEA SI, DATA_WDRAW
    CALL PRINT_STRING
    CALL SCAN_NUM
    MOV BX, CX
    MOV SI, USER_INDEX
    MOV AX, BALANCES[SI*2]
    CMP AX, BX
    JB INSUFFICIENT
    SUB BALANCES[SI*2], BX
    LEA SI, DATA_OK
    CALL PRINT_STRING
    CALL RETURN_TO_MENU
    JMP MAIN_MENU

INSUFFICIENT:
    CALL CLS
    LEA SI, DATA_FAIL
    CALL PRINT_STRING
    CALL RETURN_TO_MENU
    JMP MAIN_MENU

EXIT:
    RET

RETURN_TO_MENU:
    PRINT 0AH
    PRINT 0DH
    LEA SI, RETURN_MSG
    CALL PRINT_STRING
    CALL WAIT_KEY
    CALL CLS
    RET

CLS:
    MOV AH, 0
    MOV AL, 3
    INT 10h
    RET

WAIT_KEY:
    MOV AH, 0
    INT 16H
    RET

CODE ENDS

END START
